graph TB
    subgraph "Inputs"
        CODE[Source Code]
        API[API Endpoints]
        ARCH[Architecture<br/>Docs]
        DECIS[Design<br/>Decisions]
    end
    
    subgraph "Agent Documenteur"
        ADOC[Analyse<br/>Documentation Needs]
        GEN[Generate<br/>Content]
        VAL[Validate<br/>Completeness]
        UPD[Update<br/>Existing]
    end
    
    subgraph "Document Types"
        API_DOC[API<br/>Documentation]
        USER_G[User<br/>Guide]
        DEV_G[Developer<br/>Guide]
        DEPLOY_G[Deployment<br/>Guide]
    end
    
    subgraph "Outputs"
        DOCS[Complete<br/>Documentation]
        DIAGS[Updated<br/>Diagrams]
        CHANGELOG[Changelog]
        README[README<br/>Files]
    end
    
    CODE --> ADOC
    API --> ADOC
    ARCH --> ADOC
    DECIS --> ADOC
    
    ADOC --> GEN
    GEN --> VAL
    VAL --> UPD
    
    GEN --> API_DOC
    GEN --> USER_G
    GEN --> DEV_G
    GEN --> DEPLOY_G
    
    UPD --> DOCS
    UPD --> DIAGS
    UPD --> CHANGELOG
    UPD --> README