import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
import { WagmiConfig } from 'wagmi';
import { config, chains } from '@/lib/wagmi';

export const metadata = {
    title: 'FullSuite',
    description: 'Web3 DApp generated by SmartContractDevPipeline',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <WagmiConfig config={config}>
                    <RainbowKitProvider chains={chains}>
                        {children}
                    </RainbowKitProvider>
                </WagmiConfig>
            </body>
        </html>
    );
}
