graph TB
    subgraph "Inputs"
        TICKET[Task Ticket<br/>JIRA-like]
        ARCH[Architecture<br/>Specs]
        CODEBASE[Existing<br/>Codebase]
        TESTS[Test<br/>Requirements]
    end
    
    subgraph "Agent Codeur Workflow"
        UA[Understand<br/>Task]
        DP[Design<br/>Solution]
        IMP[Implement<br/>Code]
        UT[Unit<br/>Tests]
        REF[Refactor]
    end
    
    subgraph "Quality Gates"
        LINT[Linting]
        FORMAT[Formatting]
        STYLE[Style Check]
    end
    
    subgraph "Outputs"
        CODE[Production<br/>Code]
        UTEST[Unit Tests]
        DOCS[Inline<br/>Documentation]
        MR[Merge<br/>Request]
    end
    
    TICKET --> UA
    ARCH --> UA
    CODEBASE --> UA
    TESTS --> UA
    
    UA --> DP
    DP --> IMP
    IMP --> UT
    UT --> REF
    
    REF --> LINT
    REF --> FORMAT
    REF --> STYLE
    
    LINT --> CODE
    FORMAT --> UTEST
    STYLE --> DOCS
    
    CODE --> MR
    UTEST --> MR
    DOCS --> MR